install script breaks if not run as root

diff --git a/install b/install
--- a/install
+++ b/install
@@ -1,12 +1,12 @@
 #! /bin/bash
 export Daemondir="/opt/plancton"
 export Rundir="$Daemondir/git/run"
-export Basename=`basename $0`
+# export Basename=`basename $0`
 export Daemonuser="plancton"
 export Configrepo="https://github.com/mconcas/voluntary-config"
 
 MANUAL_DOCKER_ENABLE=no
-MANUAL_DOCKER_RESTART=no
+MANUAL_DOCKER_START=no
 MANUAL_DOCKER_INSTALL=no
 
 function welcome() {
@@ -41,24 +41,8 @@ function main() {
       
       exit 1
    fi
-   bash_c='bash -c'
-   if [[ $(id -u) != "0" ]]; then
-      if testcmd sudo; then
-         # bash_c='sudo -E sh -c'
-         echo "Relaunching as root..."
-         sudo bash -x <(curl https://raw.githubusercontent.com/mconcas/plancton/master/install) $1
-      elif testcmd su; then
-         # bash_c='su -c'
-         echo "Relaunching as root..."
-      	 su -c "exec <(curl https://raw.githubusercontent.com/mconcas/plancton/master/install) $1"
-      else
-         echo "Error: this installer needs the ability to run commands as root."
-         echo 'No "sudo" nor "su" available to make this happen.'
-         exit 1
-      fi
-      #  echo "Relaunching as root..."
-      #  exec $bash_c "exec <(curl https://raw.githubusercontent.com/mconcas/plancton/master/install) $1"
-   fi
+   
+   [[ $(id -u) != "0" ]] && echo -e "\e[1;91m [ERROR] this script needs to be run as root.\e[m" && exit 1;
 
    welcome
    testreq git pip
@@ -71,9 +55,9 @@ function main() {
       fi
    fi
    echo "restarting docker daemon..."
-   if ! service docker restart; then
+   if ! service docker start; then
       echo "couldn't, please start/restart it manually..."
-      MANUAL_DOCKER_RESTART=yes
+      MANUAL_DOCKER_START=yes
    fi
 
    (
@@ -101,7 +85,7 @@ function main() {
       if [[ "$MANUAL_DOCKER_INSTALL" == "yes" ]]; then
          echo -e " \e[1;91m * Please install docker manually\e[m"
          false
-      elif [[ "$MANUAL_DOCKER_RESTART" == "yes" ]]; then
+      elif [[ "$MANUAL_DOCKER_START" == "yes" ]]; then
          echo -e " \e[1;91m * Please start/restart docker manually\e[m"
          false
       elif [[ "$MANUAL_DOCKER_ENABLE" == "yes" ]]; then
